# Add ISO code for any locales you want to support here (space separated)
LOCALES = fr
# Name of the plugin, for the ZIP file
PLUGINNAME = your_plugin_name

docker_test:
	$(MAKE) -C qgis_plugin_tools docker_test PLUGINNAME=$(PLUGINNAME)

i18n_%:
	$(MAKE) -C qgis_plugin_tools $* LOCALES=$(LOCALES)

deploy_%:
	$(MAKE) -C qgis_plugin_tools $* PLUGINNAME=$(PLUGINNAME)
