name: flake8

on: [push, pull_request]

jobs:
  flake8_py3:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flake8
        run: |
          pip install flake8
      - name: Run flake8
        run: |
          flake8
